### ISSUE TITLE
smil:url blank

### ISSUE THREAD

**Issue by awaters1** [awaters1/plugin.video.espn_3#1]
Per kodi user:

For ESPN3, I am still getting the smilurl:none with Invalid IP for all the streams.

**Comment by awaters1** [comment]
Seems likely related to the user's ISP not supporting ESPN3 without a login.

**Comment by chovy** [comment]
I'm getting same problem.

**Comment by awaters1** [comment]
Most likely fixed with ac3c323357133daae820d815862056103a07b129
