### ISSUE TITLE
"ESPN Classic" menu item in the appletv branch mirrors "SportsCenter" item

### ISSUE THREAD

**Issue by siuside** [awaters1/plugin.video.espn_3#10]
Both seem to be calling http://espn.go.com/watchespn/appletv/sport?abbreviation=sr and ESPN Classic seems to be the bad one here. First one listed under ESPN Classic is 

`<sixteenByNinePoster id="espn-classic-shelf-2755140" accessibilityLabel="Boxing" alwaysShowTitles="true" onSelect="espn.page.loadChannelPage('http://espn.go.com/watchespn/appletv/classicListingsByProgramId?id=2755140');" onPlay="espn.page.loadChannelPage('http://espn.go.com/watchespn/appletv/classicListingsByProgramId?id=2755140');">
<image src="http://a.espncdn.com/combiner/i?img=/espn360/images/showassets/CLBOXING.jpg&w=640&h=360&20160127092448" required="false"/>
<defaultImage required="false">
<![CDATA[
http://a.espncdn.com/combiner/i?img=/espn360/images/showassets/CLBOXING.jpg&w=640&h=360&20160127092448
]]>
</defaultImage>
<title>
<![CDATA[ Boxing ]]>
</title>
<subtitle/>
<stash/>
</sixteenByNinePoster>`

**Comment by awaters1** [comment]
Should be good with 283ce7ab1a6236d7f6e40b43112333560be1a1d4

**Comment by siuside** [comment]
Yes looks great now. Thank you.
