### ISSUE TITLE
Kodi repository - Enhancement Request

### ISSUE THREAD

**Issue by siuside** [awaters1/plugin.video.espn_3#17]
Well I lied yesterday that I'd stop ;) 

Did you want to create a Kodi repo (repo.awaters1 ?) for us to be able to update automatically as you push updates to master and for future releases? 

erack has his repo here https://github.com/eracknaphobia/repo.eracknaphobia

**Comment by chovy** [comment]
This would be great. +1

**Comment by awaters1** [comment]
I think I did it correctly, here it is https://github.com/awaters1/repo.awaters1

**Comment by siuside** [comment]
Doesn't look right.

erack's repo for example is https://github.com/eracknaphobia/repo.eracknaphobia/raw/master/repository.eracknaphobia.zip

Inside the zip is the folder repository.eracknaphobia & addon.xml inside this folder. 

addon.xml in turn has the references to the raw zip files for his addons.

**Comment by awaters1** [comment]
Here is the zip https://github.com/awaters1/repo.awaters1/blob/master/repository.awaters1.zip

**Comment by siuside** [comment]
Still cant get this to install.

**Comment by awaters1** [comment]
Is there an error message? It worked for me when I tried it a week or so ago.

Archive:  repository.awaters1.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2016-06-05 19:53   repository.awaters1/
      727  2016-06-05 19:53   repository.awaters1/addon.xml
---------                     -------
      727                     2 files

**Comment by siuside** [comment]
Worked
