### ISSUE TITLE
Bitrate Setting is being too restrictive

### ISSUE THREAD

**Issue by siuside** [awaters1/plugin.video.espn_3#20]
Just launched ESPN1 and noticed couple of discrepancies.

1) With https://github.com/awaters1/plugin.video.espn_3/commit/4f06abf3fe649b977db82ea2fef06d8fdd056587 latest master) and setting bitrate setting to something really high like 20000 (or even the default 10000), the actual bitrate during the game never goes even upto 6 mbps. Also while launching the channel, get presented with https://imgur.com/gXTApmV

2) With https://github.com/awaters1/plugin.video.espn_3/commit/7c9dbe7ff27147daa551de45b32fc63ce6585d71 the prompt was for https://imgur.com/PtdCQrc and selecting the highest bitrates, I actually saw streams crossing 6 mbit sometimes.

**Comment by awaters1** [comment]
The bitrate limit setting is for the Best mode (I have made this change in the develop branch).  What it does is it lists every stream in the playlist and compares the bandwidth of the stream with the setting. As an example for your first example if the bitrate limit was set to 6500 and Best mode was selected then the stream with rate 6109k would be chosen, as opposed to the one at the top of the list.

**Comment by siuside** [comment]
Yup I understood that. What I meant was that when I chose 8953k, the stream was mostly streaming around 5mbit sometimes 5.5mbit but thats about it. It was as if my choice of selecting the best stream was not taking any effect at all. This behavior was different when the bitrate setting wasn't there, I bet the same stream would have given me 10 mbit. 

It is as if the bitrate limit is throttling unnecessarily.

**Comment by awaters1** [comment]
The bitrate limit isn't used for throttling, the number that espn lists in the playlist is the upper bound, they also have an average bandwith but it isn't in every stream so I wasn't able to use it.  Here is an example
#EXT-X-STREAM-INF:RESOLUTION=1280x720,BANDWIDTH=8072396,CODECS="mp4a.40.5,avc1.640020",FRAME-RATE=60.000,AUDIO="aac",CLOSED-CAPTIONS="ccs",AVERAGE-BANDWIDTH=6136594

about a 2000k difference between the bandwidth and average-bandwidth

**Comment by siuside** [comment]
I saw that too (and your commit for handling the avg bw). 

I just noticed better streaming with 7c9dbe7/6204k than 4f06abf/choosing 8953k for the same game. The only difference between those two was the bitrate limit in 4f06abf (mandatory one at that, but i played with 10000k and 20000k)

**Comment by awaters1** [comment]
The log says which stream was selected, something like
NOTICE: ESPN3: Chose stream 0
If it says '0' that means it chose the stream on the top, which would be the one with the highest bandwidth.  The bitrates are variable and the quality will change during the course of the event.

**Comment by siuside** [comment]
Ok I see the bw getting logged now 

`20:32:22 T:4608  NOTICE: ESPN3: Stream Quality 2
20:32:22 T:4608  NOTICE: ESPN3: bandwidth: 9649762 average bandwidth: 6160152
20:32:22 T:4608  NOTICE: ESPN3: bandwidth: 6253622 average bandwidth: 4651929
20:32:22 T:4608  NOTICE: ESPN3: bandwidth: 4107006 average bandwidth: 3181956
20:32:22 T:4608  NOTICE: ESPN3: bandwidth: 2747596 average bandwidth: 2169617
20:32:22 T:4608  NOTICE: ESPN3: bandwidth: 1549516 average bandwidth: 1222886
20:32:22 T:4608  NOTICE: ESPN3: bandwidth: 1056972 average bandwidth: 852091
20:32:22 T:4608  NOTICE: ESPN3: bandwidth: 571084 average bandwidth: 486114
20:32:26 T:4608  NOTICE: ESPN3: Chose stream 0`

Chose the highest bw for streaming 9649k and I do see good streaming now. Looks like limit is no longer selectable/changeable in the latest develop?

**Comment by awaters1** [comment]
The limit is only applicable when the Best setting is chosen.  This is so people can have the best always chosen up to a certain bit rate limit.  So I always want the best one that is under 6500k, because different channels max out at different bit rates.

**Comment by siuside** [comment]
That is just perfect. I was confused with the "Best Mode" comment earlier actually. 

But https://github.com/awaters1/plugin.video.espn_3/commit/b80d258fcdebeb289cf0a1aa54ec5a32108f6dba fixes this for us. I think this is a fantastic enhancement, perhaps going to be used most frequently than other quality options (Best Mode + a bitrate set for the individual setups). The feeds are very high bitrate otherwise for many devices to handle. 

I will try to create a wiki page dedicated to streaming quality section tomorrow.
