### ISSUE TITLE
Illegal TLS Extension

### ISSUE THREAD

**Issue by siuside** [awaters1/plugin.video.espn_3#26]
Looks like it is back with the latest develop.

http://pastebin.com/eCUDK2S3

http://prod-freewheel.espn.go.com/ seems to be some new domain in logs.

The uplynk channels are working fine (SEC/Longhorn etc)

**Comment by awaters1** [comment]
Try with this commit d9988ea6b372f79aef21765a5271513181841876

**Comment by siuside** [comment]
Didn't work. I also cleared cache just in case and saw that there was a new cookies file but still get the error.

http://pastebin.com/jWjL9kLt

**Comment by awaters1** [comment]
I cannot do anything about the TLS errors

**Comment by siuside** [comment]
I suspected so. Not sure why it started happening again, must be changes from the espn side itself.

**Comment by awaters1** [comment]
Try with cabdd0a7ae9d41a08989d55796427f8260a42347 I switched to a different platform

**Comment by siuside** [comment]
Brilliant ! That fixed it across the board. Please close issue if you are ok.

**Comment by siuside** [comment]
It looks like broadband sends these 3 extensions from the server side

-TLS server extension "renegotiation info" (id=65281), len=1
0001  `<SPACES/NULS>`
-TLS server extension "elliptic curves" (id=10), len=4
0000 - 00 02 00 17                                       ....
-TLS server extension "EC point formats" (id=11), len=2
0000 - 01                                                .
0002  `<SPACES/NULS>`
SSL_connect:SSLv3 read server hello A 

and uplynk sends these 

 -TLS server extension "renegotiation info" (id=65281), len=1
0001  `<SPACES/NULS>`
-TLS server extension "EC point formats" (id=11), len=4
0000 - 03 00 01 02                                       ....
-TLS server extension "session ticket" (id=35), len=0
SSL_connect:SSLv3 read server hello A


It would appear that broadband is incorrectly configured (not using the right TLS in apache?) to send elliptic curves extension as part of its server hello. There is a good discussion on RFC4492 (where they introduced elliptic curves extension **for clients** ) but it seems some servers have been sending this as part of their ServerHello when they shouldn't be. There is a good discussion about this in https://www.ietf.org/mail-archive/web/tls/current/msg18143.html and another one in gnutls mailing list where the author proposed and implemented this change quite a while ago https://gitlab.com/gnutls/gnutls/commit/ac64ff56b16d4d13594c6d2ba2e65b05ca555e58

I verified that this was part of [3.3.10](https://github.com/keithduncan/gnutls/blob/e3033880302c9eab512637d852f319a844743797/lib/ext/ecc.c) (not the official repo but a fork which captures source per release). The length = 4 also satisfies other checks but I can't tell from all those ifs in that code. So I am not really sure why this would fail in Jarvis which has 3.3.10.
