### ISSUE TITLE
User selectable bitrate in options - Enhancement Request

### ISSUE THREAD

**Issue by siuside** [awaters1/plugin.video.espn_3#5]
Would be great to now make the birates (1200/2200/3500/4500) selectable long with a) Always Ask b) Best Available like @eracknaphobia does for his addons.

**Comment by awaters1** [comment]
I'm just going to do Low (max 2200), Medium (max 4500) and High (max 8500).

**Comment by siuside** [comment]
Should work fine !

**Comment by siuside** [comment]
Closing this per 064713e but I do have an issue with ESPN3 Stream Selections popup not matching the actual stream quality from the m3u8. This happens only for ESPN3 streams.
