### ISSUE TITLE
ESPN3 stream quality popup doesn't match m3u8 details

### ISSUE THREAD

**Issue by siuside** [awaters1/plugin.video.espn_3#8]
Here is an example m3u8 for an event that is ongoing, but can be duplicated even with any other ESPN3 live feed or replay. 

http://xbmclogs.com/pqevn4u7a

The popup on the other hand is http://i.imgur.com/Mqfs2gc.png

This is only impacting ESPN3 feeds.

**Comment by awaters1** [comment]
The FPS is the thing that is incorrect right?

**Comment by siuside** [comment]
Yes

**Comment by awaters1** [comment]
Should be better now with 25c49823437d2f5e6a6800f522f51e63d2e5f46b

**Comment by siuside** [comment]
Going to check asap

**Comment by awaters1** [comment]
The Old Style Menu used the old function, I have updated it in ebaa4b545eb4823629923a1d651c559c99aa091f

**Comment by siuside** [comment]
Verified the fix and everything looks good in both appletv menu as well as Old Style Menu ESPN3 items.
