### ISSUE TITLE
Clear cached data behavior - Should not require re-authentication

### ISSUE THREAD

**Issue by siuside** [awaters1/plugin.video.espn_3#9]
Just backed up userdata before messing with the options to see the behavior. Upon selecting "Clear cached data", the device loses the authentication information. I think we may want to preserve the authentication at least and maybe discard other parts of cookies/selections. Perhaps only the "Defaults" settings options should remove everything.

I just wanted to change the "Ask Once" behavior but noticed that I cannot change it from the first time I had selected it which led to this workflow of testing clear cached data. Perhaps there should be a way to change the "Ask Once" behavior. I want to see how it handles going from ESPN3 30 fps stream (if this is what I first select) to a premium channel where maybe I do want the 60 fps stream

**Comment by awaters1** [comment]
Should be good with 2a153ea55f0b1bb4a7c1decf2ce54857984a0091\

The Ask Once setting saves the index of the chosen stream, so if the first stream is chosen then that setting sticks.  The streams are sorted with the best one on top, so if the 2nd best is chosen, then the 2nd best is always chosen.

**Comment by siuside** [comment]
Unable to duplicate after https://github.com/awaters1/plugin.video.espn_3/commit/bfe2bece1d8316a7504a85900140ea3d099f44fb which most likely fixed this last anomaly  after https://github.com/awaters1/plugin.video.espn_3/commit/2a153ea55f0b1bb4a7c1decf2ce54857984a0091 fixed the main issue. Regardless this should have remained closed for good. Sorry for re-opening.
